version: "3.7"

services:
  web:
    image: 127.0.0.1:5000/hello_stack
    build: .
    deploy:
      replicas: 5
      # placement:
      #   constraints:
      #     - "node.role == worker"
    ports:
      - "8005:8000"
  redis:
    image: redis:alpine
    # deploy:
    #   replicas: 2
      placement:
        constraints:
          - node.role == manager
